class AppStrings {
  static const String appName = 'FastGokdeniz';

  static Map<String, Map<String, String>> translations = {
    'tr': {
      'appName': 'FastGokdeniz',
      'home': 'Başlangıç',
      'quickConnect': 'Hızlı Bağlantı',
      'scanQR': 'QR kodunu tara',
      'socialMedia': 'Sosyal Medya',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'Email',
      'websiteQR': 'Website QR',
      'searchHistory': 'Arama Geçmişi',
      'settings': 'Ayarlar',
      'about': 'Hakkında',
      'copyrights': 'Kullanım Hakları',
      'logout': 'Çıkış Yap',
      'profile': 'Profil',
      'profileCreate': 'Profil Oluştur',
      'userName': 'Kullanıcı Adı',
      'addImage': 'Resim Ekle',
      'camera': 'Kamera ile Çek',
      'gallery': 'Galeriden Seç',
      'create': 'Oluştur',
      'cancel': 'İptal',
      'send': 'Gönder',
      'close': 'Kapat',
      'theme': 'Tema',
      'language': 'Dil',
      'darkMode': 'Koyu Mod',
      'lightMode': 'Açık Mod',
      'resetProfile': 'Profili Sıfırla',
      'enterPhoneNumber': 'Telefon Numarası Girin',
      'enterUsername': 'Kullanıcı Adı Girin',
      'enterEmail': 'Email Adresi Girin',
      'enterDiscordID': 'Discord ID Girin',
      'enterWebsiteURL': 'Website URL Girin',
      'createQR': 'QR Oluştur',
      'searchHistoryEmpty': 'Arama Geçmişi Boş',
      'developer': 'Geliştiren: Mehmet Gökdeniz',
      'allRightsReserved': 'Tüm haklar saklıdır © 2026',
      'websiteQRTitle': 'Website QR Kodu',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'Website URL',
      'enterURL': 'Lütfen URL girin',
      'aboutTitle': 'Hakkında',
      'aboutDesc':
          'Modern QR kod tarama, oluşturma ve sosyal medya entegrasyonu uygulaması. 14 farklı dil desteği ile dünya çapında kullanıcılara hizmet veriyor.',
      'features': 'Özellikler:',
      'feature1': '• QR Kod Tarama ve Oluşturma',
      'feature2': '• 14 Farklı Dil Desteği',
      'feature3': '• 5 Sosyal Medya Entegrasyonu',
      'feature4': '• Arama Geçmişi ve QR Geçmişi',
      'feature5': '• Dosya Paylaşım Linki Oluşturma',
      'feature6': '• Koyu/Açık Tema Desteği',
      'copyrightTitle': 'Kullanım Hakları',
      'openSource': 'Açık Kaynak Kütüphaneler:',
      'areYouSure': 'Emin misiniz?',
      'resetProfileConfirm':
          'Profili sıfırlamak istediğinizden emin misiniz? Bu işlem geri alınamaz.',
      'yes': 'Evet',
      'no': 'Hayır',
      'confirm': 'Sıfırla',
      'version': 'v1.0.0',
      'phoneNumber': 'Telefon Numarası',
      'loading': 'Yükleniyor...',
      'unknown': 'Bilinmiyor',
      'error': 'Hata:',
      'success': 'Başarılı',
      'facebook': 'Facebook',
      'telegram': 'Telegram',
      'youtube': 'YouTube',
      'sms': 'SMS',
      'edit': 'Düzenle',
      'viewProfile': 'Profili Görüntüle',
      'linkCreator': 'Link Oluşturucu',
      'selectFile': 'Dosya seç',
      'selectedFile': 'Seçilen dosya',
      'createDownloadLink': 'Dosya için indirme bağlantısı oluştur',
      'fileLinkCreator': 'Link Oluşturucu',
      'fileLinkCreatorSubtitle': 'Seçtiğin dosyayı paylaşmak için bağlantı üret.',
      'copyLink': 'Bağlantıyı Kopyala',
      'shareLink': 'Bağlantıyı Paylaş',
      'openLink': 'Bağlantıyı Aç',
      'uploadFile': 'Dosya Yükle',
      'downloadLink': 'İndirme Bağlantısı',
      'user': 'Kullanıcı',
      'tip1': 'QR kodlarını WhatsApp ile paylaşabilirsiniz!',
      'tip2': 'Profil fotoğrafınızı istediğiniz zaman değiştirebilirsiniz.',
      'tip3': 'Arama geçmişi otomatik olarak kayıtlanır.',
      'tip4': 'En fazla 20 arama kaydı tutulur.',
      'tip5': 'Tema ayarlarından koyu/açık modu değiştirebilirsiniz.',
      'tip6': 'Uygulamayı 14 farklı dilde kullanabilirsiniz!',
      'tip7': 'QR kodlarını kameradan ve galeriden tarayabilirsiniz.',
      'tip8': 'Discord ID\'nizi kullanarak doğrudan mesaj atabilirsiniz.',
      'tip9': 'Website QR kodunuzu özelleştirerek oluşturabilirsiniz.',
      'tip10': 'Profil sıfırlama işlemi ile tüm veriler silinir.',
      'tip11':
          'Telefon numaranızı WhatsApp olmadan SMS ile de paylaşabilirsiniz.',
      'tip12': 'Instagram kullanıcı adınızı kısa tutmak daha iyi görünür.',
      'tip13': 'X/Twitter hesabınızı email ile de doğrulayabilirsiniz.',
      'tip14': 'Arama geçmişinizden istediğiniz öğeyi silebilirsiniz.',
      'tip15': 'Telegram kanalı linki de QR kod olarak oluşturabilirsiniz.',
      'tip16': 'Facebook sayfanızı tanınırlığını artırmak için bağlayın.',
      'tip17': 'YouTube kanalınızın linkini QR koduyla paylaşın.',
      'tip18': 'Uygulama verileriniz telefonunuza kaydedilir, cloud\'da değil.',
      'tip19': 'Profil oluşturmak uygulamanın tüm özelliklerini açar.',
      'tip20': 'Arama geçmişinde most used sosyal medya platformları görülür.',
      'createdQrHistory': 'Daha önce oluşturulan QR Kodları',
      'tapToReload': 'Dokunarak yeniden yükle',
      'enterURLTitle': 'URL Girin',
      'urlExample': 'Örn: https://example.com',
      'urlHint': 'QR kod oluşturmak için URL girin',
      'yourQR': 'QR Kodunuz',
      'urlCopied': 'URL panoya kopyalandı!',
      'shareQR': 'QR Kodu Paylaş',
      'saveQR': 'QR Kodu Kaydet',
      'fileSelectError': 'Dosya seçilirken hata oluştu:',
      'qrImageError': 'QR resmi oluşturulurken hata oluştu.',
      'webShareNotSupported': 'Web üzerinde resim paylaşma desteklenmiyor.',
      'clearHistory': 'Geçmişi Temizle',
      'confirmClearHistory': 'Tüm arama geçmişini silmek istediğinizden emin misiniz?',
      'delete': 'Sil',
      'loadingFavicon': 'Site ikonu yükleniyor...',
      'copy': 'Kopyala',
      'sharePNG': 'PNG Olarak Paylaş',
      'enterQRUrl': 'QR kod oluşturmak için URL girin',
      'qrShareText': 'QR kodum burada!',
    },
    'en': {
      'appName': 'FastGokdeniz',
      'home': 'Home',
      'quickConnect': 'Quick Connect',
      'scanQR': 'Scan QR Code',
      'socialMedia': 'Social Media',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'Email',
      'websiteQR': 'Website QR',
      'searchHistory': 'Search History',
      'settings': 'Settings',
      'about': 'About',
      'copyrights': 'Copyrights',
      'logout': 'Logout',
      'profile': 'Profile',
      'profileCreate': 'Create Profile',
      'userName': 'Username',
      'addImage': 'Add Image',
      'camera': 'Take Photo',
      'gallery': 'Choose from Gallery',
      'create': 'Create',
      'cancel': 'Cancel',
      'send': 'Send',
      'close': 'Close',
      'theme': 'Theme',
      'language': 'Language',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
      'resetProfile': 'Reset Profile',
      'enterPhoneNumber': 'Enter Phone Number',
      'enterUsername': 'Enter Username',
      'enterEmail': 'Enter Email',
      'enterDiscordID': 'Enter Discord ID',
      'enterWebsiteURL': 'Enter Website URL',
      'createQR': 'Create QR',
      'searchHistoryEmpty': 'Search History Empty',
      'developer': 'Developer: Mehmet Gökdeniz',
      'allRightsReserved': 'All rights reserved © 2026',
      'websiteQRTitle': 'Website QR Code',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'Website URL',
      'enterURL': 'Please enter a URL',
      'aboutTitle': 'About',
      'aboutDesc':
          'Modern QR code scanner, generator and social media integration app. Serving users worldwide with support for 14 different languages.',
      'features': 'Features:',
      'feature1': '• QR Code Scanning and Generation',
      'feature2': '• 14 Different Language Support',
      'feature3': '• 5 Social Media Integration',
      'feature4': '• Search History and QR History',
      'feature5': '• File Sharing Link Creation',
      'feature6': '• Dark/Light Theme Support',
      'copyrightTitle': 'Copyrights',
      'openSource': 'Open Source Libraries:',
      'areYouSure': 'Are you sure?',
      'resetProfileConfirm':
          'Are you sure you want to reset your profile? This action cannot be undone.',
      'yes': 'Yes',
      'no': 'No',
      'confirm': 'Reset',
      'version': 'v1.0.0',
      'phoneNumber': 'Phone Number',
      'loading': 'Loading...',
      'unknown': 'Unknown',
      'error': 'Error:',
      'success': 'Success',
      'facebook': 'Facebook',
      'telegram': 'Telegram',
      'youtube': 'YouTube',
      'sms': 'SMS',
      'edit': 'Edit',
      'viewProfile': 'View Profile',
      'linkCreator': 'Link Creator',
      'selectFile': 'Select File',
      'selectedFile': 'Selected File',
      'createDownloadLink': 'Create downloadable link for the file',
      'fileLinkCreator': 'Link Creator',
      'fileLinkCreatorSubtitle': 'Generate a shareable download link for your selected file.',
      'copyLink': 'Copy Link',
      'shareLink': 'Share Link',
      'openLink': 'Open Link',
      'uploadFile': 'Upload File',
      'downloadLink': 'Download Link',
      'user': 'User',
      'tip1': 'You can share QR codes with WhatsApp!',
      'tip2': 'You can change your profile photo anytime.',
      'tip3': 'Search history is saved automatically.',
      'tip4': 'Maximum 20 search records are kept.',
      'tip5': 'You can switch between dark/light mode in theme settings.',
      'tip6': 'Use the app in 14 different languages!',
      'tip7': 'Scan QR codes from camera or gallery.',
      'tip8': 'Message directly using your Discord ID.',
      'tip9': 'Create customized website QR codes.',
      'tip10': 'Profile reset will delete all your data.',
      'tip11': 'Share your phone number via SMS even without WhatsApp.',
      'tip12': 'Keep your Instagram username short for better appearance.',
      'tip13': 'You can verify your X/Twitter account with email.',
      'tip14': 'Delete any item from your search history.',
      'tip15': 'Create QR codes for your Telegram channel links.',
      'tip16': 'Link your Facebook page to increase recognition.',
      'tip17': 'Share your YouTube channel link with QR code.',
      'tip18': 'App data is saved on your phone, not in the cloud.',
      'tip19': 'Creating a profile unlocks all app features.',
      'tip20': 'See your most used social media platforms in search history.',
      'createdQrHistory': 'Previously Created QR Codes',
      'tapToReload': 'Tap to reload',
      'enterURLTitle': 'Enter URL',
      'urlExample': 'e.g: https://example.com',
      'urlHint': 'Enter URL to create QR code',
      'yourQR': 'Your QR Code',
      'urlCopied': 'URL copied to clipboard!',
      'shareQR': 'Share QR Code',
      'saveQR': 'Save QR Code',
      'fileSelectError': 'Error selecting file:',
      'qrImageError': 'Error creating QR image.',
      'webShareNotSupported': 'Image sharing not supported on web.',
      'clearHistory': 'Clear History',
      'confirmClearHistory': 'Are you sure you want to clear all search history?',
      'delete': 'Delete',
      'loadingFavicon': 'Loading site icon...',
      'copy': 'Copy',
      'sharePNG': 'Share as PNG',
      'enterQRUrl': 'Enter URL to create QR code',
      'qrShareText': 'Here is my QR code!',
    },
    'ar': {
      'appName': 'فاست جوكدنيز',
      'home': 'الصفحة الرئيسية',
      'quickConnect': 'اتصال سريع',
      'scanQR': 'مسح رمز QR',
      'socialMedia': 'وسائل التواصل الاجتماعي',
      'whatsapp': 'واتس آب',
      'instagram': 'إنستجرام',
      'x': 'X',
      'discord': 'ديسكورد',
      'email': 'بريد إلكتروني',
      'websiteQR': 'رمز QR للموقع',
      'searchHistory': 'سجل البحث',
      'settings': 'الإعدادات',
      'about': 'حول',
      'copyrights': 'حقوق النشر',
      'logout': 'تسجيل الخروج',
      'profile': 'الملف الشخصي',
      'profileCreate': 'إنشاء ملف شخصي',
      'userName': 'اسم المستخدم',
      'addImage': 'إضافة صورة',
      'camera': 'التقط صورة',
      'gallery': 'اختر من المعرض',
      'create': 'إنشاء',
      'cancel': 'إلغاء',
      'send': 'إرسال',
      'close': 'إغلاق',
      'theme': 'المظهر',
      'language': 'اللغة',
      'darkMode': 'الوضع الداكن',
      'lightMode': 'الوضع الفاتح',
      'resetProfile': 'إعادة تعيين الملف الشخصي',
      'enterPhoneNumber': 'أدخل رقم الهاتف',
      'enterUsername': 'أدخل اسم المستخدم',
      'enterEmail': 'أدخل بريدك الإلكتروني',
      'enterDiscordID': 'أدخل معرف Discord',
      'enterWebsiteURL': 'أدخل عنوان الموقع',
      'createQR': 'إنشاء QR',
      'searchHistoryEmpty': 'سجل البحث فارغ',
      'developer': 'المطور: محمد جوكدنيز',
      'allRightsReserved': 'جميع الحقوق محفوظة © 2026',
      'websiteQRTitle': 'رمز QR للموقع',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'عنوان الموقع',
      'enterURL': 'يرجى إدخال عنوان موقع',
      'aboutTitle': 'حول',
      'aboutDesc':
          'تطبيق حديث لمسح رموز QR والمولد وتطبيق تكامل وسائل التواصل الاجتماعي. يخدم المستخدمين في جميع أنحاء العالم بدعم 14 لغة مختلفة.',
      'features': 'الميزات:',
      'feature1': '• مسح وتوليد رموز QR',
      'feature2': '• دعم 14 لغة مختلفة',
      'feature3': '• تكامل 5 وسائل التواصل الاجتماعي',
      'feature4': '• سجل البحث وتاريخ QR',
      'feature5': '• إنشاء روابط مشاركة الملفات',
      'feature6': '• دعم المظهر الداكن/الفاتح',
      'copyrightTitle': 'حقوق النشر',
      'openSource': 'مكتبات مفتوحة المصدر:',
      'areYouSure': 'هل أنت متأكد؟',
      'resetProfileConfirm':
          'هل تريد فعلاً إعادة تعيين ملفك الشخصي؟ لا يمكن التراجع عن هذا الإجراء.',
      'yes': 'نعم',
      'no': 'لا',
      'confirm': 'إعادة تعيين',
      'version': 'v1.0.0',
      'phoneNumber': 'رقم الهاتف',
      'loading': 'جاري التحميل...',
      'unknown': 'غير معروف',
      'error': 'خطأ:',
      'success': 'نجح',
      'facebook': 'فيس بوك',
      'telegram': 'تيليجرام',
      'youtube': 'يوتيوب',
      'sms': 'رسالة نصية',
      'edit': 'تحرير',
      'user': 'المستخدم',
      'tip1': 'يمكنك مشاركة رموز QR عبر WhatsApp!',
      'tip2': 'يمكنك تغيير صورة ملفك الشخصي في أي وقت.',
      'tip3': 'يتم حفظ سجل البحث تلقائياً.',
      'tip4': 'يتم الاحتفاظ بحد أقصى 20 سجل بحث.',
      'tip5': 'يمكنك التبديل بين الوضع الداكن/الفاتح في إعدادات المظهر.',
      'tip6': 'استخدم التطبيق في 14 لغة مختلفة!',
      'tip7': 'قم بمسح رموز QR من الكاميرا أو المعرض.',
      'tip8': 'راسل مباشرة باستخدام معرف Discord الخاص بك.',
      'tip9': 'إنشاء رموز QR للموقع مخصصة.',
      'tip10': 'سيؤدي إعادة تعيين الملف الشخصي إلى حذف جميع بيانات المستخدم.',
      'tip11': 'شارك رقم هاتفك عبر SMS حتى بدون WhatsApp.',
      'tip12': 'اختر اسم مستخدم Instagram قصيراً لمظهر أفضل.',
      'tip13': 'يمكنك التحقق من حساب X/Twitter باستخدام البريد الإلكتروني.',
      'tip14': 'احذف أي عنصر من سجل البحث الخاص بك.',
      'tip15': 'أنشئ رموز QR لروابط قنوات Telegram.',
      'tip16': 'ربط صفحة Facebook الخاصة بك لزيادة الاعتراف.',
      'tip17': 'شارك رابط قناة YouTube الخاصة بك برمز QR.',
      'tip18': 'يتم حفظ بيانات التطبيق على الهاتف وليس في السحابة.',
      'tip19': 'ينفتح إنشاء ملف شخصي جميع ميزات التطبيق.',
      'tip20':
          'شاهد منصات وسائل التواصل الاجتماعي الأكثر استخداماً في سجل البحث.',
      'createdQrHistory': 'رموز QR المُنشأة سابقاً',
      'tapToReload': 'اضغط لإعادة التحميل',
      'enterURLTitle': 'أدخل عنوان الموقع',
      'urlExample': 'مثال: https://example.com',
      'urlHint': 'أدخل عنوان الموقع لإنشاء رمز QR',
      'yourQR': 'رمز QR الخاص بك',
      'urlCopied': 'تم نسخ عنوان الموقع إلى الحافظة!',
      'shareQR': 'مشاركة رمز QR',
      'saveQR': 'حفظ رمز QR',
      'fileSelectError': 'خطأ في اختيار الملف:',
      'qrImageError': 'خطأ في إنشاء صورة QR.',
      'webShareNotSupported': 'مشاركة الصور غير مدعومة على الويب.',
      'clearHistory': 'مسح التاريخ',
      'confirmClearHistory': 'هل أنت متأكد من أنك تريد مسح كل تاريخ البحث؟',
      'delete': 'حذف',
      'loadingFavicon': 'تحميل أيقونة الموقع...',
      'copy': 'نسخ',
      'sharePNG': 'مشاركة كـ PNG',
      'enterQRUrl': 'أدخل عنوان الموقع لإنشاء رمز QR',
      'qrShareText': 'إليك رمز QR الخاص بي!',
    },
    'fr': {
      'appName': 'FastGokdeniz',
      'home': 'Accueil',
      'quickConnect': 'Connexion rapide',
      'scanQR': 'Scanner le code QR',
      'socialMedia': 'Réseaux sociaux',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'Email',
      'websiteQR': 'QR du site Web',
      'searchHistory': 'Historique de recherche',
      'settings': 'Paramètres',
      'about': 'À propos',
      'copyrights': 'Droits d\'auteur',
      'logout': 'Déconnexion',
      'profile': 'Profil',
      'profileCreate': 'Créer un profil',
      'userName': 'Nom d\'utilisateur',
      'addImage': 'Ajouter une image',
      'camera': 'Prendre une photo',
      'gallery': 'Choisir dans la galerie',
      'create': 'Créer',
      'cancel': 'Annuler',
      'send': 'Envoyer',
      'close': 'Fermer',
      'theme': 'Thème',
      'language': 'Langue',
      'darkMode': 'Mode sombre',
      'lightMode': 'Mode clair',
      'resetProfile': 'Réinitialiser le profil',
      'enterPhoneNumber': 'Entrez le numéro de téléphone',
      'enterUsername': 'Entrez le nom d\'utilisateur',
      'enterEmail': 'Entrez l\'adresse email',
      'enterDiscordID': 'Entrez l\'ID Discord',
      'enterWebsiteURL': 'Entrez l\'URL du site Web',
      'createQR': 'Créer QR',
      'searchHistoryEmpty': 'Historique de recherche vide',
      'developer': 'Développeur: Mehmet Gökdeniz',
      'allRightsReserved': 'Tous droits réservés © 2026',
      'websiteQRTitle': 'Code QR du site Web',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'URL du site Web',
      'enterURL': 'Veuillez entrer une URL',
      'aboutTitle': 'À propos',
      'aboutDesc':
          'Application moderne de scanner de code QR, générateur et intégration des réseaux sociaux. Servant les utilisateurs dans le monde entier avec le support de 14 langues différentes.',
      'features': 'Caractéristiques:',
      'feature1': '• Scan et génération de codes QR',
      'feature2': '• Support de 14 langues différentes',
      'feature3': '• Intégration de 5 réseaux sociaux',
      'feature4': '• Historique de recherche et historique QR',
      'feature5': '• Création de liens de partage de fichiers',
      'feature6': '• Support du thème sombre/clair',
      'copyrightTitle': 'Droits d\'auteur',
      'openSource': 'Bibliothèques open source:',
      'areYouSure': 'Êtes-vous sûr?',
      'resetProfileConfirm':
          'Êtes-vous sûr de vouloir réinitialiser votre profil? Cette action ne peut pas être annulée.',
      'yes': 'Oui',
      'no': 'Non',
      'confirm': 'Réinitialiser',
      'version': 'v1.0.0',
      'phoneNumber': 'Numéro de téléphone',
      'loading': 'Chargement...',
      'unknown': 'Inconnu',
      'error': 'Erreur:',
      'success': 'Succès',
      'facebook': 'Facebook',
      'telegram': 'Telegram',
      'youtube': 'YouTube',
      'sms': 'SMS',
      'edit': 'Modifier',
      'user': 'Utilisateur',
      'tip1': 'Vous pouvez partager des codes QR via WhatsApp!',
      'tip2': 'Vous pouvez changer votre photo de profil à tout moment.',
      'tip3': 'L\'historique de recherche est enregistré automatiquement.',
      'tip4': 'Un maximum de 20 recherches est conservé.',
      'tip5':
          'Vous pouvez basculer entre le thème sombre/clair dans les paramètres d\'apparence.',
      'tip6': 'Utilisez l\'application dans 14 langues différentes!',
      'tip7':
          'Scannez les codes QR à partir de l\'appareil photo ou de la galerie.',
      'tip8': 'Messagez directement avec votre ID Discord.',
      'tip9': 'Créez des codes QR de site Web personnalisés.',
      'tip10':
          'La réinitialisation du profil supprimera toutes les données utilisateur.',
      'tip11': 'Partagez votre numéro de téléphone via SMS même sans WhatsApp.',
      'tip12':
          'Choisissez un nom d\'utilisateur Instagram court pour une meilleure apparence.',
      'tip13':
          'Vous pouvez vérifier votre compte X/Twitter à l\'aide de l\'e-mail.',
      'tip14':
          'Supprimez n\'importe quel élément de votre historique de recherche.',
      'tip15': 'Créez des codes QR pour les liens de canal Telegram.',
      'tip16': 'Liez votre page Facebook pour une reconnaissance accrue.',
      'tip17': 'Partagez le lien de votre chaîne YouTube via code QR.',
      'tip18':
          'Les données de l\'application sont enregistrées sur votre téléphone, pas dans le cloud.',
      'tip19':
          'La création d\'un profil déverrouille toutes les fonctionnalités de l\'application.',
      'tip20':
          'Consultez les plateformes de médias sociaux les plus utilisées dans l\'historique de recherche.',
      'createdQrHistory': 'Codes QR créés précédemment',
      'tapToReload': 'Appuyez pour recharger',
      'enterURLTitle': 'Entrez l\'URL',
      'urlExample': 'ex: https://example.com',
      'urlHint': 'Entrez l\'URL pour créer le code QR',
      'yourQR': 'Votre code QR',
      'urlCopied': 'URL copiée dans le presse-papiers!',
      'shareQR': 'Partager le code QR',
      'saveQR': 'Enregistrer le code QR',
      'fileSelectError': 'Erreur lors de la sélection du fichier:',
      'qrImageError': 'Erreur lors de la création de l\'image QR.',
      'webShareNotSupported': 'Partage d\'image non pris en charge sur le web.',
      'clearHistory': 'Effacer l\'historique',
      'confirmClearHistory': 'Êtes-vous sûr de vouloir effacer tout l\'historique de recherche?',
      'delete': 'Supprimer',
      'loadingFavicon': 'Chargement de l\'icône du site...',
      'copy': 'Copier',
      'sharePNG': 'Partager en PNG',
      'enterQRUrl': 'Entrez l\'URL pour créer le code QR',
      'qrShareText': 'Voici mon code QR!',
    },
    'ja': {
      'appName': 'FastGokdeniz',
      'home': 'ホーム',
      'quickConnect': 'クイック接続',
      'socialMedia': 'ソーシャルメディア',
      'websiteQR': 'ウェブサイトQR',
      'quickConnect': 'クイック接続',
      'scanQR': 'QRコードをスキャン',
      'socialMedia': 'ソーシャルメディア',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'メール',
      'websiteQR': 'ウェブサイトQR',
      'searchHistory': '検索履歴',
      'settings': '設定',
      'about': 'について',
      'copyrights': '著作権',
      'logout': 'ログアウト',
      'profile': 'プロフィール',
      'profileCreate': 'プロフィールを作成',
      'userName': 'ユーザー名',
      'addImage': '画像を追加',
      'camera': '写真を撮る',
      'gallery': 'ギャラリーから選択',
      'create': '作成',
      'cancel': 'キャンセル',
      'send': '送信',
      'close': '閉じる',
      'theme': 'テーマ',
      'language': '言語',
      'darkMode': 'ダークモード',
      'lightMode': 'ライトモード',
      'resetProfile': 'プロフィールをリセット',
      'enterPhoneNumber': '電話番号を入力',
      'enterUsername': 'ユーザー名を入力',
      'enterEmail': 'メールアドレスを入力',
      'enterDiscordID': 'Discord IDを入力',
      'enterWebsiteURL': 'ウェブサイトURLを入力',
      'createQR': 'QRを作成',
      'searchHistoryEmpty': '検索履歴が空です',
      'developer': '開発者: メフメット ゴクデニズ',
      'allRightsReserved': '著作権所有 © 2026',
      'websiteQRTitle': 'ウェブサイトQRコード',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'ウェブサイトURL',
      'enterURL': 'URLを入力してください',
      'aboutTitle': 'について',
      'aboutDesc': 'QRコードスキャナー、ジェネレーター、ソーシャルメディア統合アプリケーション。',
      'features': '特徴:',
      'feature1': '• QRコードスキャン',
      'feature2': '• QRコード生成',
      'feature3': '• 6つのソーシャルメディア統合',
      'feature4': '• 検索履歴',
      'copyrightTitle': '著作権',
      'openSource': 'オープンソースライブラリ:',
      'areYouSure': 'よろしいですか?',
      'resetProfileConfirm': '本当にプロフィールをリセットしますか?このアクションは元に戻すことができません。',
      'yes': 'はい',
      'no': 'いいえ',
      'confirm': 'リセット',
      'version': 'v1.0.0',
      'phoneNumber': '電話番号',
      'loading': '読み込み中...',
      'unknown': '不明',
      'error': 'エラー:',
      'success': '成功',
      'facebook': 'Facebook',
      'telegram': 'Telegram',
      'youtube': 'YouTube',
      'sms': 'SMS',
      'edit': '編集',
      'user': 'ユーザー',
      'tip1': 'WhatsAppでQRコードを共有できます!',
      'tip2': 'プロフィール写真はいつでも変更できます。',
      'tip3': '検索履歴は自動的に保存されます。',
      'tip4': '最大20個の検索が保持されます。',
      'tip5': '外観設定ダークモード/ライトモードを切り替えることができます。',
      'tip6': '6つの異なる言語でアプリケーションを使用してください!',
      'tip7': 'カメラまたはギャラリーからQRコードをスキャンします。',
      'tip8': 'Discord IDを使ってメッセージを直接送信します。',
      'tip9': 'カスタムウェブサイトQRコードを作成します。',
      'tip10': 'プロフィールをリセットするとすべてのユーザーデータが削除されます。',
      'tip11': 'WhatsAppなしでもSMS経由で電話番号を共有します。',
      'tip12': 'より良い外観のために短いInstagramユーザー名を選択してください。',
      'tip13': '電子メールを使用してX/Twitterアカウントを確認できます。',
      'tip14': '検索履歴から任意のアイテムを削除します。',
      'tip15': 'Telegramチャネルリンク用のQRコードを作成します。',
      'tip16': 'Facebookページをリンクして認識を向上させます。',
      'tip17': 'QRコード経由でYouTubeチャネルリンクを共有します。',
      'tip18': 'アプリケーションデータはクラウドではなくスマートフォンに保存されます。',
      'tip19': 'プロフィールを作成するとすべてのアプリ機能がロック解除されます。',
      'tip20': '検索履歴で最も使用されているソーシャルメディアプラットフォームを表示します。',
      'createdQrHistory': '以前に作成されたQRコード',
      'tapToReload': 'タップして再ロード',
      'enterURLTitle': 'URLを入力',
      'urlExample': '例：https://example.com',
      'urlHint': 'QRコードを作成するにはURLを入力してください',
      'yourQR': 'あなたのQRコード',
      'urlCopied': 'URLがクリップボードにコピーされました！',
      'loadingFavicon': 'サイトアイコンを読み込み中...',
      'copy': 'コピー',
      'sharePNG': 'PNGとして共有',
      'enterQRUrl': 'QRコードを作成するにはURLを入力してください',
      'qrShareText': 'ここに私のQRコードがあります！',
      'fileSelectError': 'ファイル選択中にエラーが発生しました：',
      'qrImageError': 'QR画像の作成中にエラーが発生しました。',
      'webShareNotSupported': 'Web上での画像共有はサポートされていません。',
    },
    'ku': {
      'appName': 'FastGokdeniz',
      'home': 'Malper',
      'quickConnect': 'Girêdanên Bilez',
      'socialMedia': 'Medyaya Civata',
      'websiteQR': 'Malperan QR',
      'quickConnect': 'Girêdanên Bilez',
      'scanQR': 'QR Code Scan Bike',
      'socialMedia': 'Medyaya Civata',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'E-peyam',
      'websiteQR': 'Malperan QR',
      'searchHistory': 'Dîroka Lêgerînê',
      'settings': 'Mîhenk',
      'about': 'Derbar',
      'copyrights': 'Mafên Neqil',
      'logout': 'Derket',
      'profile': 'Profîl',
      'profileCreate': 'Profîleke Nû Biafirîne',
      'userName': 'Navê Bikarhêner',
      'addImage': 'Wêneyek Zêde Bike',
      'camera': 'Wêne Bigire',
      'gallery': 'Ji Galeriyê Hilbijêre',
      'create': 'Biafirîne',
      'cancel': 'Betal Bike',
      'send': 'Bişîne',
      'close': 'Bigire',
      'theme': 'Temaye',
      'language': 'Ziman',
      'darkMode': 'Moda Tarî',
      'lightMode': 'Moda Ronahî',
      'resetProfile': 'Profîlê Vegerande Bike',
      'enterPhoneNumber': 'Hejmarê Telefona Tikîne',
      'enterUsername': 'Navê Bikarhêner Tikîne',
      'enterEmail': 'E-peyama Xwe Tikîne',
      'enterDiscordID': 'Discord ID Tikîne',
      'enterWebsiteURL': 'URL-ya Malpera Tikîne',
      'createQR': 'QR Biafirîne',
      'searchHistoryEmpty': 'Dîroka Lêgerînê Vala ye',
      'developer': 'Pêsazker: Mehmet Gökdeniz',
      'allRightsReserved': 'Hemû Maf Veqetandî © 2026',
      'websiteQRTitle': 'QR Code ya Malpera',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'URL-ya Malpera',
      'enterURL': 'Kerema xwe URL-ya bikêne',
      'aboutTitle': 'Derbar',
      'aboutDesc':
          'Sepana Scanning QR Code, Generator û Yekîtiya Medyaya Civata.',
      'features': 'Taybetmendî:',
      'feature1': '• QR Code Scanning',
      'feature2': '• QR Code Hilberandin',
      'feature3': '• Yekîtiya 6 Medyaya Civata',
      'feature4': '• Dîroka Lêgerînê',
      'copyrightTitle': 'Mafên Neqil',
      'openSource': 'Pirtûkxaneyên Çavkaniya Vekirî:',
      'areYouSure': 'Tu ramînt î?',
      'resetProfileConfirm':
          'Tu ramînt î ku tu dixwazî profîla xwe vegerande bikî? Ev çalakî nabe ku bersivdêr bibe.',
      'yes': 'Erê',
      'no': 'Na',
      'confirm': 'Vegerande Bike',
      'version': 'v1.0.0',
      'phoneNumber': 'Hejmarê Telefona',
      'loading': 'Barkirina Navber...',
      'unknown': 'Nenas',
      'error': 'Çewtiyek:',
      'success': 'Serkeftî',
      'facebook': 'Facebook',
      'telegram': 'Telegram',
      'youtube': 'YouTube',
      'sms': 'SMS',
      'edit': 'Biguherîne',
      'user': 'Bikarhêner',
      'tip1': 'Hûn dikarin kodên QR bi WhatsAppî parve bikin!',
      'tip2': 'Hûn dikarin wêneya profîlê xwe her dem biguherîne.',
      'tip3': 'Dîroka lêgerînê bi xwezayî tomar dibe.',
      'tip4': 'Ya herî zêde 20 lêgerîn têne çêkirin.',
      'tip5':
          'Hûn dikarin dema navidên xuyang de di navbeyna moda tarî/ronahî de biguherîne.',
      'tip6': 'Sepa bikar bînin di 6 zimanên cuda de!',
      'tip7': 'Kodên QR ji kamerayê an galeriyê scan bikin.',
      'tip8': 'Rasterast bi ID Discord-a xwe peyvî bikin.',
      'tip9': 'Kodên QR ên malpera xweser ava bikin.',
      'tip10': 'Vegerandina profîlê hemî daneyên bikarhêner dê jê bibe.',
      'tip11': 'Hejmarê telefona xwe bi SMS-ê parve bikin tewra bê WhatsApp.',
      'tip12':
          'Ji bo xuyangeke çêtir navê bikarhêner Instagram-ê kurtahî hilbijêre.',
      'tip13':
          'Hûn dikarin hesabê X/Twitter-a xwe bi e-peyamê tê misdawî bikin.',
      'tip14': 'Casî tiştekî ji dîroka lêgerînê xwe jê bibe.',
      'tip15': 'Kodên QR ji bo girêdanên kanalê Telegram ava bikin.',
      'tip16': 'Malpera Facebook-a xwe girêbidin ji bo naskirin zêde bike.',
      'tip17': 'Girêdana kanalê YouTube-a xwe bi kodan QR parve bikin.',
      'tip18': 'Daneyên sepayê li ser telefona xwe ne hilkestin di cloud-ê de.',
      'tip19': 'Ava kiriyana profîlê hemî taybetmendiyên sepayê vala dikin.',
      'tip20':
          'Platforma medyaya civata yên herî geştî yên di dîroka lêgerînê de bibîn.',
      'createdQrHistory': 'QR Kodên Berê Avakirî',
      'tapToReload': 'Bitikîne da ku nuhûnî bikêşe',
      'enterURLTitle': 'URL Tikîne',
      'urlExample': 'mînak: https://example.com',
      'urlHint': 'URL-ya bikêne da ku QR Code ava bikî',
      'yourQR': 'QR Koda Te',
      'urlCopied': 'URL-ya vê klîpbordê hat kopî kirin!',
      'loadingFavicon': 'Nîşana malperê barkirina navber...',
      'copy': 'Kopî Bike',
      'sharePNG': 'Wek PNG Parve Bike',
      'enterQRUrl': 'URL-ya bikêne da ku QR Code ava bikî',
      'qrShareText': 'QR kodem vira ye!',
      'fileSelectError': 'Demê têna dosyeyê: ',
      'qrImageError': 'Demê xêzkirina QR: ',
      'webShareNotSupported': 'Di malperan de parvekirina wêneyê nayê piştgirtin.',
    },
    'hi': {
      'appName': 'FastGokdeniz',
      'home': 'होम',
      'quickConnect': 'त्वरित जुड़ें',
      'socialMedia': 'सोशल मीडिया',
      'websiteQR': 'वेबसाइट QR',
      'quickConnect': 'त्वरित कनेक्ट',
      'scanQR': 'QR कोड स्कैन करें',
      'socialMedia': 'सोशल मीडिया',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'ईमेल',
      'websiteQR': 'वेबसाइट QR',
      'searchHistory': 'खोज इतिहास',
      'settings': 'सेटिंग्स',
      'about': 'हमारे बारे में',
      'copyrights': 'कॉपीराइट',
      'logout': 'लॉग आउट',
      'profile': 'प्रोफ़ाइल',
      'profileCreate': 'प्रोफ़ाइल बनाएं',
      'userName': 'उपयोगकर्ता नाम',
      'addImage': 'छवि जोड़ें',
      'camera': 'कैमरा से लें',
      'gallery': 'गैलरी से चुनें',
      'create': 'बनाएं',
      'cancel': 'रद्द करें',
      'send': 'भेजें',
      'close': 'बंद करें',
      'theme': 'थीम',
      'language': 'भाषा',
      'darkMode': 'डार्क मोड',
      'lightMode': 'लाइट मोड',
      'resetProfile': 'प्रोफ़ाइल रीसेट करें',
      'enterPhoneNumber': 'फोन नंबर दर्ज करें',
      'enterUsername': 'उपयोगकर्ता नाम दर्ज करें',
      'enterEmail': 'ईमेल दर्ज करें',
      'enterDiscordID': 'Discord ID दर्ज करें',
      'enterWebsiteURL': 'वेबसाइट URL दर्ज करें',
      'createQR': 'QR बनाएं',
      'searchHistoryEmpty': 'खोज इतिहास खाली है',
      'developer': 'डेवलपर: Mehmet Gökdeniz',
      'allRightsReserved': 'सर्वाधिकार सुरक्षित © 2026',
      'websiteQRTitle': 'वेबसाइट QR कोड',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'वेबसाइट URL',
      'enterURL': 'कृपया URL दर्ज करें',
      'aboutTitle': 'हमारे बारे में',
      'aboutDesc': 'QR कोड स्कैनिंग, निर्माण और सोशल मीडिया एकीकरण ऐप।',
      'feature1': '• QR कोड स्कैनिंग',
      'feature2': '• QR कोड निर्माण',
      'feature3': '• सोशल मीडिया एकीकरण',
      'feature4': '• खोज इतिहास',
      'copyrightTitle': 'कॉपीराइट',
      'openSource': 'ओपन सोर्स लाइब्रेरीज़:',
      'areYouSure': 'क्या आप निश्चित हैं?',
      'resetProfileConfirm':
          'क्या आप अपनी प्रोफ़ाइल रीसेट करना चाहते हैं? यह क्रिया अपरिवर्तनीय है।',
      'yes': 'हाँ',
      'no': 'नहीं',
      'confirm': 'रीसेट करें',
      'version': 'v1.0.0',
      'phoneNumber': 'फोन नंबर',
      'loading': 'लोड हो रहा है...',
      'tip1': 'आप WhatsApp के माध्यम से QR कोड साझा कर सकते हैं!',
      'tip2': 'आप कभी भी अपनी प्रोफ़ाइल छवि बदल सकते हैं।',
      'tip3': 'खोज इतिहास स्वचालित रूप से सहेजा जाता है।',
      'tip4': 'अधिकतम 20 खोजें संग्रहीत की जाती हैं।',
      'tip5': 'आप नाइट मोड में डार्क/लाइट मोड के बीच स्विच कर सकते हैं।',
      'tip6': '6 अलग-अलग भाषाओं में ऐप का उपयोग करें!',
      'tip7': 'कैमरा या गैलरी से QR कोड स्कैन करें।',
      'tip8': 'अपने Discord ID से सीधे संपर्क करें।',
      'tip9': 'स्वतंत्र वेबसाइट QR कोड बनाएं।',
      'tip10': 'प्रोफ़ाइल रीसेट सभी उपयोगकर्ता डेटा को हटा देगा।',
      'tip11': 'WhatsApp के बिना भी SMS के माध्यम से अपना फोन नंबर साझा करें।',
      'tip12': 'QR कोड को PNG के रूप में सहेजें और साझा करें।',
      'tip13': 'अपनी प्रोफ़ाइल छवि पर टैप करके उसे बड़ा करें।',
      'tip14': 'सभी प्लेटफ़ॉर्म पर एक ही QR कोड का उपयोग करें।',
      'tip15': 'अपने डेटा को JSON या CSV के रूप में निर्यात करें।',
      'tip16': 'अधिक पहचान के लिए अपने Facebook पेज से लिंक करें।',
      'tip17': 'QR कोड के साथ अपने YouTube चैनल लिंक साझा करें।',
      'tip18': 'ऐप डेटा आपके फोन पर क्लाउड में नहीं अपलोड होता।',
      'tip19': 'प्रोफ़ाइल निर्माण ऐप की सभी सुविधाओं को रीसेट करता है।',
      'tip20': 'खोज इतिहास में सबसे लोकप्रिय सोशल मीडिया प्लेटफ़ॉर्म देखें।',
      'createdQrHistory': 'पहले बनाए गए QR कोड',
      'tapToReload': 'पुनः लोड करने के लिए टैप करें',
      'enterURLTitle': 'URL दर्ज करें',
      'urlExample': 'उदा: https://example.com',
      'urlHint': 'QR कोड बनाने के लिए URL दर्ज करें',
      'yourQR': 'आपका QR कोड',
      'urlCopied': 'URL क्लिपबोर्ड पर कॉपी किया गया!',
      'loadingFavicon': 'साइट आइकन लोड हो रहा है...',
      'copy': 'कॉपी करें',
      'sharePNG': 'PNG के रूप में शेयर करें',
      'enterQRUrl': 'QR कोड बनाने के लिए URL दर्ज करें',
      'qrShareText': 'यहाँ मेरा QR कोड है!',
      'fileSelectError': 'फ़ाइल चयन में त्रुटि: ',
      'qrImageError': 'QR छवि बनाने में त्रुटि।',
      'webShareNotSupported': 'वेब पर छवि साझा करना समर्थित नहीं है।',
    },
    'ru': {
      'appName': 'FastGokdeniz',
      'home': 'Главная',
      'quickConnect': 'Быстрое подключение',
      'scanQR': 'Сканировать QR-код',
      'socialMedia': 'Социальные сети',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'Email',
      'websiteQR': 'QR-код сайта',
      'searchHistory': 'История поиска',
      'settings': 'Настройки',
      'about': 'О приложении',
      'copyrights': 'Авторские права',
      'logout': 'Выйти',
      'profile': 'Профиль',
      'profileCreate': 'Создать профиль',
      'userName': 'Имя пользователя',
      'addImage': 'Добавить изображение',
      'camera': 'Сфотографировать',
      'gallery': 'Выбрать из галереи',
      'create': 'Создать',
      'cancel': 'Отмена',
      'send': 'Отправить',
      'close': 'Закрыть',
      'theme': 'Тема',
      'language': 'Язык',
      'darkMode': 'Темный режим',
      'lightMode': 'Светлый режим',
      'resetProfile': 'Сбросить профиль',
      'enterPhoneNumber': 'Введите номер телефона',
      'enterUsername': 'Введите имя пользователя',
      'enterEmail': 'Введите email',
      'enterDiscordID': 'Введите Discord ID',
      'enterWebsiteURL': 'Введите URL сайта',
      'createQR': 'Создать QR',
      'searchHistoryEmpty': 'История поиска пуста',
      'developer': 'Разработчик: Mehmet Gökdeniz',
      'allRightsReserved': 'Все права защищены © 2026',
      'websiteQRTitle': 'QR-код сайта',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'URL сайта',
      'enterURL': 'Пожалуйста, введите URL',
      'aboutTitle': 'О приложении',
      'aboutDesc':
          'Приложение для сканирования, создания QR-кодов и интеграции с социальными сетями.',
      'feature1': '• Сканирование QR-кодов',
      'feature2': '• Создание QR-кодов',
      'feature3': '• Интеграция с соцсетями',
      'feature4': '• История поиска',
      'copyrightTitle': 'Авторские права',
      'openSource': 'Библиотеки с открытым исходным кодом:',
      'areYouSure': 'Вы уверены?',
      'resetProfileConfirm':
          'Вы уверены, что хотите сбросить профиль? Это действие необратимо.',
      'yes': 'Да',
      'no': 'Нет',
      'confirm': 'Сбросить',
      'version': 'v1.0.0',
      'phoneNumber': 'Номер телефона',
      'loading': 'Загрузка...',
      'tip1': 'Вы можете делиться QR-кодами через WhatsApp!',
      'tip2': 'Вы можете в любое время изменить фото профиля.',
      'tip3': 'История поиска сохраняется автоматически.',
      'tip4': 'Сохраняется максимум 20 поисков.',
      'tip5': 'В ночном режиме можно переключаться между темной/светлой темой.',
      'tip6': 'Используйте приложение на 6 разных языках!',
      'tip7': 'Сканируйте QR-коды с камеры или из галереи.',
      'tip8': 'Свяжитесь напрямую по вашему Discord ID.',
      'tip9': 'Создавайте независимые QR-коды сайтов.',
      'tip10': 'Сброс профиля удалит все пользовательские данные.',
      'tip11': 'Делитесь номером телефона через SMS даже без WhatsApp.',
      'tip12': 'Сохраняйте и делитесь QR-кодами в формате PNG.',
      'tip13': 'Нажмите на фото профиля, чтобы увеличить его.',
      'tip14': 'Используйте один QR-код на всех платформах.',
      'tip15': 'Экспортируйте данные в формате JSON или CSV.',
      'tip16': 'Свяжите свою страницу Facebook для большей узнаваемости.',
      'tip17': 'Делитесь ссылкой на свой YouTube-канал с помощью QR-кодов.',
      'tip18': 'Данные приложения не загружаются в облако с вашего телефона.',
      'tip19': 'Создание профиля сбрасывает все функции приложения.',
      'tip20':
          'Просмотрите самые популярные платформы социальных сетей в истории поиска.',
      'createdQrHistory': 'Ранее созданные QR-коды',
      'tapToReload': 'Нажмите для перезагрузки',
      'enterURLTitle': 'Введите URL',
      'urlExample': 'напр: https://example.com',
      'urlHint': 'Введите URL для создания QR-кода',
      'yourQR': 'Ваш QR-код',
      'urlCopied': 'URL скопирован в буфер обмена!',
      'loadingFavicon': 'Загрузка значка сайта...',
      'copy': 'Копировать',
      'sharePNG': 'Поделиться PNG',
      'enterQRUrl': 'Введите URL для создания QR-кода',
      'qrShareText': 'Вот мой QR-код!',
      'fileSelectError': 'Ошибка выбора файла: ',
      'qrImageError': 'Ошибка создания изображения QR.',
      'webShareNotSupported': 'Совместное использование изображений в Интернете не поддерживается.',
    },
    'de': {
      'appName': 'FastGokdeniz',
      'home': 'Startseite',
      'quickConnect': 'Schnellverbindung',
      'socialMedia': 'Soziale Medien',
      'websiteQR': 'Website QR',
      'quickConnect': 'Schnellverbindung',
      'scanQR': 'QR-Code scannen',
      'socialMedia': 'Soziale Medien',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'E-Mail',
      'websiteQR': 'Website QR',
      'searchHistory': 'Suchverlauf',
      'settings': 'Einstellungen',
      'about': 'Über uns',
      'copyrights': 'Urheberrechte',
      'logout': 'Abmelden',
      'profile': 'Profil',
      'profileCreate': 'Profil erstellen',
      'userName': 'Benutzername',
      'addImage': 'Bild hinzufügen',
      'camera': 'Mit Kamera aufnehmen',
      'gallery': 'Aus Galerie wählen',
      'create': 'Erstellen',
      'cancel': 'Abbrechen',
      'send': 'Senden',
      'close': 'Schließen',
      'theme': 'Thema',
      'language': 'Sprache',
      'darkMode': 'Dunkler Modus',
      'lightMode': 'Heller Modus',
      'resetProfile': 'Profil zurücksetzen',
      'enterPhoneNumber': 'Telefonnummer eingeben',
      'enterUsername': 'Benutzernamen eingeben',
      'enterEmail': 'E-Mail eingeben',
      'enterDiscordID': 'Discord ID eingeben',
      'enterWebsiteURL': 'Website-URL eingeben',
      'createQR': 'QR erstellen',
      'searchHistoryEmpty': 'Suchverlauf ist leer',
      'developer': 'Entwickler: Mehmet Gökdeniz',
      'allRightsReserved': 'Alle Rechte vorbehalten © 2026',
      'websiteQRTitle': 'Website QR-Code',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'Website-URL',
      'enterURL': 'Bitte URL eingeben',
      'aboutTitle': 'Über uns',
      'aboutDesc':
          'QR-Code-Scanning, -Erstellung und Social-Media-Integration-App.',
      'feature1': '• QR-Code-Scanning',
      'feature2': '• QR-Code-Erstellung',
      'feature3': '• Social-Media-Integration',
      'feature4': '• Suchverlauf',
      'copyrightTitle': 'Urheberrechte',
      'openSource': 'Open-Source-Bibliotheken:',
      'areYouSure': 'Sind Sie sicher?',
      'resetProfileConfirm':
          'Sind Sie sicher, dass Sie Ihr Profil zurücksetzen möchten? Diese Aktion ist irreversibel.',
      'yes': 'Ja',
      'no': 'Nein',
      'confirm': 'Zurücksetzen',
      'version': 'v1.0.0',
      'phoneNumber': 'Telefonnummer',
      'loading': 'Lädt...',
      'tip1': 'Sie können QR-Codes über WhatsApp teilen!',
      'tip2': 'Sie können Ihr Profilbild jederzeit ändern.',
      'tip3': 'Der Suchverlauf wird automatisch gespeichert.',
      'tip4': 'Maximal 20 Suchen werden gespeichert.',
      'tip5':
          'Im Nachtmodus können Sie zwischen dunklem/hellem Modus wechseln.',
      'tip6': 'Verwenden Sie die App in 6 verschiedenen Sprachen!',
      'tip7': 'Scannen Sie QR-Codes von der Kamera oder aus der Galerie.',
      'tip8': 'Kontaktieren Sie direkt über Ihre Discord-ID.',
      'tip9': 'Erstellen Sie unabhängige Website-QR-Codes.',
      'tip10': 'Das Zurücksetzen des Profils löscht alle Benutzerdaten.',
      'tip11': 'Teilen Sie Ihre Telefonnummer per SMS, auch ohne WhatsApp.',
      'tip12': 'Speichern und teilen Sie QR-Codes als PNG.',
      'tip13': 'Tippen Sie auf Ihr Profilbild, um es zu vergrößern.',
      'tip14': 'Verwenden Sie denselben QR-Code auf allen Plattformen.',
      'tip15': 'Exportieren Sie Daten als JSON oder CSV.',
      'tip16': 'Verlinken Sie Ihre Facebook-Seite für mehr Sichtbarkeit.',
      'tip17': 'Teilen Sie den Link zu Ihrem YouTube-Kanal mit QR-Codes.',
      'tip18':
          'App-Daten werden nicht von Ihrem Telefon in die Cloud hochgeladen.',
      'tip19': 'Die Profilerstellung setzt alle App-Funktionen zurück.',
      'tip20':
          'Sehen Sie die beliebtesten Social-Media-Plattformen im Suchverlauf.',
      'createdQrHistory': 'Zuvor erstellte QR-Codes',
      'tapToReload': 'Zum Neuladen tippen',
      'enterURLTitle': 'URL eingeben',
      'urlExample': 'z.B: https://example.com',
      'urlHint': 'Geben Sie URL ein, um QR-Code zu erstellen',
      'yourQR': 'Ihr QR-Code',
      'urlCopied': 'URL in Zwischenablage kopiert!',
      'loadingFavicon': 'Website-Symbol wird geladen...',
      'copy': 'Kopieren',
      'sharePNG': 'Als PNG teilen',
      'enterQRUrl': 'Geben Sie URL ein, um QR-Code zu erstellen',
      'qrShareText': 'Hier ist mein QR-Code!',
      'fileSelectError': 'Fehler bei Dateiauswahl: ',
      'qrImageError': 'Fehler beim Erstellen des QR-Bildes.',
      'webShareNotSupported': 'Bildfreigabe im Internet wird nicht unterstützt.',
    },
    'pt': {
      'appName': 'FastGokdeniz',
      'home': 'Início',
      'quickConnect': 'Conexão Rápida',
      'socialMedia': 'Redes Sociais',
      'websiteQR': 'QR do Site',
      'quickConnect': 'Conexão Rápida',
      'scanQR': 'Escanear QR Code',
      'socialMedia': 'Redes Sociais',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'Email',
      'websiteQR': 'QR do Site',
      'searchHistory': 'Histórico de Pesquisa',
      'settings': 'Configurações',
      'about': 'Sobre',
      'copyrights': 'Direitos Autorais',
      'logout': 'Sair',
      'profile': 'Perfil',
      'profileCreate': 'Criar Perfil',
      'userName': 'Nome de Usuário',
      'addImage': 'Adicionar Imagem',
      'camera': 'Tirar Foto',
      'gallery': 'Escolher da Galeria',
      'create': 'Criar',
      'cancel': 'Cancelar',
      'send': 'Enviar',
      'close': 'Fechar',
      'theme': 'Tema',
      'language': 'Idioma',
      'darkMode': 'Modo Escuro',
      'lightMode': 'Modo Claro',
      'resetProfile': 'Redefinir Perfil',
      'enterPhoneNumber': 'Digite o Número do Telefone',
      'enterUsername': 'Digite o Nome de Usuário',
      'enterEmail': 'Digite o Email',
      'enterDiscordID': 'Digite o ID do Discord',
      'enterWebsiteURL': 'Digite a URL do Site',
      'createQR': 'Criar QR',
      'searchHistoryEmpty': 'Histórico de Pesquisa Vazio',
      'developer': 'Desenvolvedor: Mehmet Gökdeniz',
      'allRightsReserved': 'Todos os direitos reservados © 2026',
      'websiteQRTitle': 'Código QR do Site',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'URL do Site',
      'enterURL': 'Por favor, digite a URL',
      'aboutTitle': 'Sobre',
      'aboutDesc':
          'App de escaneamento, criação de QR codes e integração com redes sociais.',
      'feature1': '• Escaneamento de QR Codes',
      'feature2': '• Criação de QR Codes',
      'feature3': '• Integração com Redes Sociais',
      'feature4': '• Histórico de Pesquisa',
      'copyrightTitle': 'Direitos Autorais',
      'openSource': 'Bibliotecas de Código Aberto:',
      'areYouSure': 'Você tem certeza?',
      'resetProfileConfirm':
          'Você tem certeza de que deseja redefinir seu perfil? Esta ação é irreversível.',
      'yes': 'Sim',
      'no': 'Não',
      'confirm': 'Redefinir',
      'version': 'v1.0.0',
      'phoneNumber': 'Número do Telefone',
      'loading': 'Carregando...',
      'tip1': 'Você pode compartilhar códigos QR via WhatsApp!',
      'tip2': 'Você pode alterar sua foto de perfil a qualquer momento.',
      'tip3': 'O histórico de pesquisa é salvo automaticamente.',
      'tip4': 'São armazenadas no máximo 20 pesquisas.',
      'tip5': 'No modo noturno, você pode alternar entre tema escuro/claro.',
      'tip6': 'Use o app em 6 idiomas diferentes!',
      'tip7': 'Escaneie códigos QR da câmera ou da galeria.',
      'tip8': 'Conecte-se diretamente pelo seu ID do Discord.',
      'tip9': 'Crie códigos QR independentes de sites.',
      'tip10': 'Redefinir perfil excluirá todos os dados do usuário.',
      'tip11':
          'Compartilhe seu número de telefone via SMS, mesmo sem WhatsApp.',
      'tip12': 'Salve e compartilhe códigos QR em formato PNG.',
      'tip13': 'Toque na foto do perfil para ampliá-la.',
      'tip14': 'Use o mesmo código QR em todas as plataformas.',
      'tip15': 'Exporte dados em formato JSON ou CSV.',
      'tip16': 'Vincule sua página do Facebook para mais reconhecimento.',
      'tip17': 'Compartilhe o link do seu canal do YouTube com códigos QR.',
      'tip18': 'Os dados do app não são enviados para a nuvem do seu telefone.',
      'tip19': 'Criar perfil redefine todas as funções do app.',
      'tip20':
          'Veja as plataformas de redes sociais mais populares no histórico de pesquisa.',
      'createdQrHistory': 'Códigos QR Criados Anteriormente',
      'tapToReload': 'Toque para recarregar',
      'enterURLTitle': 'Digite a URL',
      'urlExample': 'ex: https://example.com',
      'urlHint': 'Digite a URL para criar código QR',
      'yourQR': 'Seu Código QR',
      'urlCopied': 'URL copiada para a área de transferência!',
      'loadingFavicon': 'Carregando ícone do site...',
      'copy': 'Copiar',
      'sharePNG': 'Compartilhar como PNG',
      'enterQRUrl': 'Digite a URL para criar código QR',
      'qrShareText': 'Aqui está meu código QR!',
      'fileSelectError': 'Erro ao selecionar arquivo: ',
      'qrImageError': 'Erro ao criar imagem QR.',
      'webShareNotSupported': 'Compartilhamento de imagem não suportado na web.',
    },
    'ko': {
      'appName': 'FastGokdeniz',
      'home': '홈',
      'quickConnect': '빠른 연결',
      'socialMedia': '소셜 미디어',
      'websiteQR': '웹사이트 QR',
      'quickConnect': '빠른 연결',
      'scanQR': 'QR 코드 스캔',
      'socialMedia': '소셜 미디어',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': '이메일',
      'websiteQR': '웹사이트 QR',
      'searchHistory': '검색 기록',
      'settings': '설정',
      'about': '정보',
      'copyrights': '저작권',
      'logout': '로그아웃',
      'profile': '프로필',
      'profileCreate': '프로필 생성',
      'userName': '사용자 이름',
      'addImage': '이미지 추가',
      'camera': '카메라로 촬영',
      'gallery': '갤러리에서 선택',
      'create': '생성',
      'cancel': '취소',
      'send': '전송',
      'close': '닫기',
      'theme': '테마',
      'language': '언어',
      'darkMode': '다크 모드',
      'lightMode': '라이트 모드',
      'resetProfile': '프로필 재설정',
      'enterPhoneNumber': '전화번호 입력',
      'enterUsername': '사용자 이름 입력',
      'enterEmail': '이메일 입력',
      'enterDiscordID': 'Discord ID 입력',
      'enterWebsiteURL': '웹사이트 URL 입력',
      'createQR': 'QR 생성',
      'searchHistoryEmpty': '검색 기록이 비어 있습니다',
      'developer': '개발자: Mehmet Gökdeniz',
      'allRightsReserved': '모든 권리 보유 © 2026',
      'websiteQRTitle': '웹사이트 QR 코드',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': '웹사이트 URL',
      'enterURL': 'URL을 입력하세요',
      'aboutTitle': '정보',
      'aboutDesc': 'QR 코드 스캔, 생성 및 소셜 미디어 통합 앱입니다.',
      'feature1': '• QR 코드 스캔',
      'feature2': '• QR 코드 생성',
      'feature3': '• 소셜 미디어 통합',
      'feature4': '• 검색 기록',
      'copyrightTitle': '저작권',
      'openSource': '오픈 소스 라이브러리:',
      'areYouSure': '확실합니까?',
      'resetProfileConfirm': '프로필을 재설정하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
      'yes': '예',
      'no': '아니오',
      'confirm': '재설정',
      'version': 'v1.0.0',
      'phoneNumber': '전화번호',
      'loading': '로딩 중...',
      'tip1': 'WhatsApp을 통해 QR 코드를 공유할 수 있습니다!',
      'tip2': '언제든지 프로필 사진을 변경할 수 있습니다.',
      'tip3': '검색 기록이 자동으로 저장됩니다.',
      'tip4': '최대 20개의 검색이 저장됩니다.',
      'tip5': '야간 모드에서 다크/라이트 모드 간 전환할 수 있습니다.',
      'tip6': '6가지 다른 언어로 앱을 사용하세요!',
      'tip7': '카메라나 갤러리에서 QR 코드를 스캔하세요.',
      'tip8': 'Discord ID로 직접 연락하세요.',
      'tip9': '독립적인 웹사이트 QR 코드를 생성하세요.',
      'tip10': '프로필 재설정으로 모든 사용자 데이터가 삭제됩니다.',
      'tip11': 'WhatsApp 없이도 SMS로 전화번호를 공유하세요.',
      'tip12': 'QR 코드를 PNG로 저장하고 공유하세요.',
      'tip13': '프로필 사진을 탭하여 확대하세요.',
      'tip14': '모든 플랫폼에서 동일한 QR 코드를 사용하세요.',
      'tip15': '데이터를 JSON 또는 CSV로 내보내세요.',
      'tip16': '더 많은 인지도를 위해 Facebook 페이지를 연결하세요.',
      'tip17': 'QR 코드로 YouTube 채널 링크를 공유하세요.',
      'tip18': '앱 데이터가 귀하의 전화기에서 클라우드로 업로드되지 않습니다.',
      'tip19': '프로필 생성으로 앱의 모든 기능을 재설정합니다.',
      'tip20': '검색 기록에서 가장 인기 있는 소셜 미디어 플랫폼을 확인하세요.',
      'createdQrHistory': '이전에 생성된 QR 코드',
      'tapToReload': '탭하여 다시 로드',
      'enterURLTitle': 'URL 입력',
      'urlExample': '예: https://example.com',
      'urlHint': 'QR 코드를 생성하려면 URL을 입력하세요',
      'yourQR': '당신의 QR 코드',
      'urlCopied': 'URL이 클립보드에 복사되었습니다!',
      'loadingFavicon': '사이트 아이콘 로드 중...',
      'copy': '복사',
      'sharePNG': 'PNG로 공유',
      'enterQRUrl': 'QR 코드를 생성하려면 URL을 입력하세요',
      'qrShareText': '내 QR 코드입니다!',
      'fileSelectError': '파일 선택 오류: ',
      'qrImageError': 'QR 이미지 생성 오류입니다.',
      'webShareNotSupported': '웹에서는 이미지 공유가 지원되지 않습니다.',
    },
    'zh': {
      'appName': 'FastGokdeniz',
      'home': '首页',
      'quickConnect': '快速连接',
      'socialMedia': '社交媒体',
      'websiteQR': '网站二维码',
      'quickConnect': '快速连接',
      'scanQR': '扫描二维码',
      'socialMedia': '社交媒体',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': '邮箱',
      'websiteQR': '网站二维码',
      'searchHistory': '搜索历史',
      'settings': '设置',
      'about': '关于',
      'copyrights': '版权',
      'logout': '登出',
      'profile': '个人资料',
      'profileCreate': '创建个人资料',
      'userName': '用户名',
      'addImage': '添加图片',
      'camera': '拍照',
      'gallery': '从相册选择',
      'create': '创建',
      'cancel': '取消',
      'send': '发送',
      'close': '关闭',
      'theme': '主题',
      'language': '语言',
      'darkMode': '深色模式',
      'lightMode': '浅色模式',
      'resetProfile': '重置个人资料',
      'enterPhoneNumber': '输入电话号码',
      'enterUsername': '输入用户名',
      'enterEmail': '输入邮箱',
      'enterDiscordID': '输入Discord ID',
      'enterWebsiteURL': '输入网站URL',
      'createQR': '创建二维码',
      'searchHistoryEmpty': '搜索历史为空',
      'developer': '开发者: Mehmet Gökdeniz',
      'allRightsReserved': '版权所有 © 2026',
      'websiteQRTitle': '网站二维码',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': '网站URL',
      'enterURL': '请输入URL',
      'aboutTitle': '关于',
      'aboutDesc': '二维码扫描、创建和社交媒体集成的应用程序。',
      'feature1': '• 二维码扫描',
      'feature2': '• 二维码创建',
      'feature3': '• 社交媒体集成',
      'feature4': '• 搜索历史',
      'copyrightTitle': '版权',
      'openSource': '开源库:',
      'areYouSure': '您确定吗？',
      'resetProfileConfirm': '您确定要重置个人资料吗？此操作不可逆。',
      'yes': '是',
      'no': '否',
      'confirm': '重置',
      'version': 'v1.0.0',
      'phoneNumber': '电话号码',
      'loading': '加载中...',
      'tip1': '您可以通过WhatsApp分享二维码！',
      'tip2': '您可以随时更改个人资料照片。',
      'tip3': '搜索历史自动保存。',
      'tip4': '最多保存20次搜索。',
      'tip5': '在夜间模式下可以在深色/浅色模式之间切换。',
      'tip6': '使用6种不同语言的应用程序！',
      'tip7': '从相机或相册扫描二维码。',
      'tip8': '通过您的Discord ID直接联系。',
      'tip9': '创建独立的网站二维码。',
      'tip10': '重置个人资料将删除所有用户数据。',
      'tip11': '即使没有WhatsApp，也可以通过SMS分享电话号码。',
      'tip12': '将二维码保存为PNG并分享。',
      'tip13': '点击个人资料照片将其放大。',
      'tip14': '在所有平台上使用相同的二维码。',
      'tip15': '将数据导出为JSON或CSV。',
      'tip16': '链接您的Facebook页面以获得更多认可。',
      'tip17': '使用二维码分享您的YouTube频道链接。',
      'tip18': '应用程序数据不会从您的手机上传到云端。',
      'tip19': '创建个人资料会重置应用程序的所有功能。',
      'tip20': '在搜索历史中查看最受欢迎的社交媒体平台。',
      'createdQrHistory': '之前创建的QR码',
      'tapToReload': '轻按重新加载',
      'enterURLTitle': '输入URL',
      'urlExample': '例：https://example.com',
      'urlHint': '输入URL以创建QR码',
      'yourQR': '您的QR码',
      'urlCopied': 'URL已复制到剪贴板！',
      'loadingFavicon': '正在加载网站图标...',
      'copy': '复制',
      'sharePNG': '分享为PNG',
      'enterQRUrl': '输入URL以创建QR码',
      'qrShareText': '这是我的QR码！',
      'fileSelectError': '选择文件时出错：',
      'qrImageError': '创建QR图像时出错。',
      'webShareNotSupported': '网络上不支持共享图像。',
    },
    'it': {
      'appName': 'FastGokdeniz',
      'home': 'Pagina Iniziale',
      'quickConnect': 'Connessione Rapida',
      'scanQR': 'Scansiona QR Code',
      'socialMedia': 'Reti Sociali',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'Email',
      'websiteQR': 'QR Sito Web',
      'searchHistory': 'Cronologia Ricerca',
      'settings': 'Impostazioni',
      'about': 'Informazioni',
      'copyrights': 'Diritti d\'autore',
      'logout': 'Esci',
      'profile': 'Profilo',
      'profileCreate': 'Crea Profilo',
      'userName': 'Nome Utente',
      'addImage': 'Aggiungi Immagine',
      'camera': 'Scatta Foto',
      'gallery': 'Scegli dalla Galleria',
      'create': 'Crea',
      'cancel': 'Annulla',
      'send': 'Invia',
      'close': 'Chiudi',
      'theme': 'Tema',
      'language': 'Lingua',
      'darkMode': 'Modalità Scura',
      'lightMode': 'Modalità Chiara',
      'resetProfile': 'Ripristina Profilo',
      'enterPhoneNumber': 'Inserisci Numero di Telefono',
      'enterUsername': 'Inserisci Nome Utente',
      'enterEmail': 'Inserisci Email',
      'enterDiscordID': 'Inserisci ID Discord',
      'enterWebsiteURL': 'Inserisci URL Sito Web',
      'createQR': 'Crea QR',
      'searchHistoryEmpty': 'Cronologia Ricerca Vuota',
      'developer': 'Sviluppatore: Mehmet Gökdeniz',
      'allRightsReserved': 'Tutti i diritti riservati © 2026',
      'websiteQRTitle': 'Codice QR Sito Web',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'URL Sito Web',
      'enterURL': 'Inserisci URL',
      'aboutTitle': 'Informazioni',
      'aboutDesc':
          'App per scansione, creazione codici QR e integrazione social media.',
      'feature1': '• Scansione Codici QR',
      'feature2': '• Creazione Codici QR',
      'feature3': '• Integrazione Social Media',
      'feature4': '• Cronologia Ricerca',
      'copyrightTitle': 'Diritti d\'autore',
      'openSource': 'Librerie Open Source:',
      'areYouSure': 'Sei sicuro?',
      'resetProfileConfirm':
          'Sei sicuro di voler ripristinare il profilo? Questa azione è irreversibile.',
      'yes': 'Sì',
      'no': 'No',
      'confirm': 'Ripristina',
      'version': 'v1.0.0',
      'phoneNumber': 'Numero di Telefono',
      'loading': 'Caricamento...',
      'tip1': 'Puoi condividere codici QR tramite WhatsApp!',
      'tip2': 'Puoi cambiare la foto del profilo in qualsiasi momento.',
      'tip3': 'La cronologia ricerca viene salvata automaticamente.',
      'tip4': 'Vengono salvate al massimo 20 ricerche.',
      'tip5': 'In modalità notturna puoi passare dalla modalità scura/chiara.',
      'tip6': 'Usa l\'app in 6 lingue diverse!',
      'tip7': 'Scansiona codici QR dalla fotocamera o dalla galleria.',
      'tip8': 'Contatta direttamente tramite il tuo ID Discord.',
      'tip9': 'Crea codici QR indipendenti per siti web.',
      'tip10': 'Il ripristino del profilo eliminerà tutti i dati utente.',
      'tip11':
          'Condividi il tuo numero di telefono via SMS, anche senza WhatsApp.',
      'tip12': 'Salva e condividi codici QR in formato PNG.',
      'tip13': 'Tocca la foto del profilo per ingrandirla.',
      'tip14': 'Usa lo stesso codice QR su tutte le piattaforme.',
      'tip15': 'Esporta dati in formato JSON o CSV.',
      'tip16': 'Collega la tua pagina Facebook per maggiore riconoscimento.',
      'tip17': 'Condividi il link del tuo canale YouTube con codici QR.',
      'tip18':
          'I dati dell\'app non vengono caricati nel cloud dal tuo telefono.',
      'tip19':
          'La creazione del profilo ripristina tutte le funzioni dell\'app.',
      'tip20':
          'Visualizza le piattaforme social più popolari nella cronologia ricerca.',
      'createdQrHistory': 'Codici QR Creati Precedentemente',
      'tapToReload': 'Tocca per ricaricare',
      'enterURLTitle': 'Inserisci URL',
      'urlExample': 'es: https://example.com',
      'urlHint': 'Inserisci URL per creare codice QR',
      'yourQR': 'Il Tuo Codice QR',
      'urlCopied': 'URL copiato negli appunti!',
      'loadingFavicon': 'Caricamento icona del sito...',
      'copy': 'Copia',
      'sharePNG': 'Condividi come PNG',
      'enterQRUrl': 'Inserisci URL per creare codice QR',
      'qrShareText': 'Ecco il mio codice QR!',
      'fileSelectError': 'Errore nella selezione del file: ',
      'qrImageError': 'Errore nella creazione dell\'immagine QR.', 'websiteQR': 'QR Sito Web',
      'webShareNotSupported': 'Condivisione immagini non supportata sul web.',
      'websiteQR': 'QR Sito Web',
    },
    'es': {
      'appName': 'FastGokdeniz',
      'home': 'Inicio',
      'quickConnect': 'Conexión Rápida',
      'socialMedia': 'Redes Sociales',
      'websiteQR': 'QR del Sitio Web',
      'quickConnect': 'Conexión Rápida',
      'scanQR': 'Escanear Código QR',
      'socialMedia': 'Redes Sociales',
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'x': 'X',
      'discord': 'Discord',
      'email': 'Correo',
      'websiteQR': 'QR de Sitio Web',
      'searchHistory': 'Historial de Búsqueda',
      'settings': 'Configuraciones',
      'about': 'Acerca de',
      'copyrights': 'Derechos de Autor',
      'logout': 'Cerrar Sesión',
      'profile': 'Perfil',
      'profileCreate': 'Crear Perfil',
      'userName': 'Nombre de Usuario',
      'addImage': 'Agregar Imagen',
      'camera': 'Tomar Foto',
      'gallery': 'Elegir de Galería',
      'create': 'Crear',
      'cancel': 'Cancelar',
      'send': 'Enviar',
      'close': 'Cerrar',
      'theme': 'Tema',
      'language': 'Idioma',
      'darkMode': 'Modo Oscuro',
      'lightMode': 'Modo Claro',
      'resetProfile': 'Restablecer Perfil',
      'enterPhoneNumber': 'Ingrese Número de Teléfono',
      'enterUsername': 'Ingrese Nombre de Usuario',
      'enterEmail': 'Ingrese Correo',
      'enterDiscordID': 'Ingrese ID de Discord',
      'enterWebsiteURL': 'Ingrese URL del Sitio Web',
      'createQR': 'Crear QR',
      'searchHistoryEmpty': 'Historial de Búsqueda Vacío',
      'developer': 'Desarrollador: Mehmet Gökdeniz',
      'allRightsReserved': 'Todos los derechos reservados © 2026',
      'websiteQRTitle': 'Código QR del Sitio Web',
      'websiteQRHint': 'https://example.com',
      'websiteQRLabel': 'URL del Sitio Web',
      'enterURL': 'Por favor ingrese URL',
      'aboutTitle': 'Acerca de',
      'aboutDesc':
          'Aplicación de escaneo, creación de códigos QR e integración con redes sociales.',
      'feature1': '• Escaneo de Códigos QR',
      'feature2': '• Creación de Códigos QR',
      'feature3': '• Integración con Redes Sociales',
      'feature4': '• Historial de Búsqueda',
      'copyrightTitle': 'Derechos de Autor',
      'openSource': 'Bibliotecas de Código Abierto:',
      'areYouSure': '¿Está seguro?',
      'resetProfileConfirm':
          '¿Está seguro de que desea restablecer su perfil? Esta acción es irreversible.',
      'yes': 'Sí',
      'no': 'No',
      'confirm': 'Restablecer',
      'version': 'v1.0.0',
      'phoneNumber': 'Número de Teléfono',
      'loading': 'Cargando...',
      'tip1': '¡Puede compartir códigos QR a través de WhatsApp!',
      'tip2': 'Puede cambiar su foto de perfil en cualquier momento.',
      'tip3': 'El historial de búsqueda se guarda automáticamente.',
      'tip4': 'Se almacenan máximo 20 búsquedas.',
      'tip5': 'En modo nocturno puede alternar entre modo oscuro/claro.',
      'tip6': '¡Use la app en 6 idiomas diferentes!',
      'tip7': 'Escanee códigos QR desde la cámara o la galería.',
      'tip8': 'Conéctese directamente por su ID de Discord.',
      'tip9': 'Cree códigos QR independientes de sitios web.',
      'tip10': 'Restablecer perfil eliminará todos los datos de usuario.',
      'tip11': 'Comparta su número de teléfono por SMS, incluso sin WhatsApp.',
      'tip12': 'Guarde y comparta códigos QR en formato PNG.',
      'tip13': 'Toque la foto de perfil para ampliarla.',
      'tip14': 'Use el mismo código QR en todas las plataformas.',
      'tip15': 'Exporte datos en formato JSON o CSV.',
      'tip16': 'Vincule su página de Facebook para mayor reconocimiento.',
      'tip17': 'Comparta el enlace de su canal de YouTube con códigos QR.',
      'tip18': 'Los datos de la app no se suben a la nube desde su teléfono.',
      'tip19': 'Crear perfil restablece todas las funciones de la app.',
      'tip20':
          'Vea las plataformas de redes sociales más populares en el historial de búsqueda.',
      'createdQrHistory': 'Códigos QR Creados Anteriormente',
      'tapToReload': 'Toque para recargar',
      'enterURLTitle': 'Ingrese URL',
      'urlExample': 'ej: https://example.com',
      'urlHint': 'Ingrese URL para crear código QR',
      'yourQR': 'Su Código QR',
      'urlCopied': '¡URL copiada al portapapeles!',
      'loadingFavicon': 'Cargando icono del sitio...',
      'copy': 'Copiar',
      'sharePNG': 'Compartir como PNG',
      'enterQRUrl': 'Ingrese URL para crear código QR',
      'qrShareText': '¡Aquí está mi código QR!',
      'fileSelectError': 'Error al seleccionar archivo: ',
      'qrImageError': 'Error al crear imagen QR.',
      'webShareNotSupported': 'Compartir imágenes no se admite en la web.',
    },
  };

  static String get(String key, String language) {
    final translated = translations[language]?[key];
    if (translated != null && translated.isNotEmpty) {
      return translated;
    }
    return translations['tr']?[key] ?? key;
  }
}
